/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Logo3.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function LogoModel(props) {
  const { nodes, materials } = useGLTF('/Logo3.glb')
  return (
    <group {...props} dispose={null}>
      <group>
      <mesh geometry={nodes.Curve001.geometry} material={materials['SVGMat.001']} position={[0.2, 0, 2.3]} rotation={[Math.PI / 2, 0, 0]} scale={[40, 15, 40]}>
            <shaderMaterial vertexShader={shader.vertexShader} fragmentShader={shader.fragmentShader} />
        </mesh>
      </group>
    </group>
  )
}



const shader = {
  vertexShader: `
      varying vec2 vUv;
      void main() {
        vUv = uv;
        gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
      }
    `,
  fragmentShader: `
      void main() {
        gl_FragColor = vec4(.95,.80,0.0,1.0);
      }
    `,
};


useGLTF.preload('/Logo3.glb')
